common-files:
    littleshops,massiveshops:
        [templates/404.liquid,config/settings_data.json]
massiveshops:
    develop:
        password: '$massiveshops_pass'
        theme_id: '$massiveshops_dev'
        store: '$massiveshops_store_url'
    master:
        password: '$massiveshops_pass'
        theme_id: '$massiveshops_master'
        store: '$massiveshops_store_url'
littleshops:
    develop:
        password: '$littleshops_pass'
        theme_id: '$littleshops_dev'
        store: '$littleshops_store_url'
    master:
        password: '$littleshops_pass'
        theme_id: '$littleshops_master'
        store: '$littleshops_store_url'
